# Generated by Django 3.0.4 on 2020-03-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('desciption', models.CharField(max_length=10000)),
                ('is_op', models.BooleanField()),
            ],
        ),
    ]
