# Generated by Django 3.0.7 on 2020-06-24 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0002_auto_20200622_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='content_choices',
            field=models.ManyToManyField(blank=True, to='discuss.content_types'),
        ),
        migrations.AlterField(
            model_name='ask',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
