# Generated by Django 3.0.4 on 2020-03-21 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0003_auto_20200321_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relation',
            old_name='from_id',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='relation',
            old_name='to_id',
            new_name='target_id',
        ),
    ]
