# Generated by Django 3.0.7 on 2020-06-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0003_auto_20200624_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='ask',
            name='image',
            field=models.ImageField(blank=True, upload_to='ask_images/'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='description',
            field=models.TextField(),
        ),
    ]
