# Generated by Django 3.0.4 on 2020-03-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0004_auto_20200321_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=10000, null=True),
        ),
        migrations.CreateModel(
            name='context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_url', models.CharField(max_length=1000)),
                ('contents', models.ManyToManyField(to='discuss.topic')),
            ],
        ),
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('topics', models.ManyToManyField(to='discuss.topic')),
            ],
        ),
    ]
