# Generated by Django 3.0.7 on 2020-06-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0004_auto_20200630_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='image',
            field=models.ImageField(blank=True, upload_to='ask_images'),
        ),
    ]
