# Generated by Django 3.0.4 on 2020-03-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0005_auto_20200324_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='contents',
            field=models.ManyToManyField(to='discuss.content'),
        ),
    ]
