# Generated by Django 3.0.7 on 2020-06-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0005_auto_20200630_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='ask_images'),
        ),
    ]
