# Generated by Django 3.0.4 on 2020-03-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0006_auto_20200324_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='is_op',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
