# Generated by Django 3.0.4 on 2020-03-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0007_auto_20200324_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='context',
            name='contents',
        ),
        migrations.AddField(
            model_name='content',
            name='contexts',
            field=models.ManyToManyField(to='discuss.context'),
        ),
    ]
