# Generated by Django 3.0.4 on 2020-03-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0010_auto_20200327_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='content_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
