# Generated by Django 3.0.4 on 2020-03-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0011_content_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='ask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('content_choice', models.ManyToManyField(to='discuss.content_types')),
            ],
        ),
    ]
