# Generated by Django 3.0.4 on 2020-03-29 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0012_ask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ask',
            old_name='content_choice',
            new_name='content_choices',
        ),
    ]
