# Generated by Django 3.0.4 on 2020-03-29 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0013_auto_20200329_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=10000)),
                ('ask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discuss.ask')),
            ],
        ),
    ]
