# Generated by Django 3.0.4 on 2020-03-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0015_comment_comment_relation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='is_op',
        ),
        migrations.AlterField(
            model_name='content',
            name='topics',
            field=models.ManyToManyField(to='discuss.Topic'),
        ),
        migrations.DeleteModel(
            name='relation',
        ),
    ]
