# Generated by Django 3.0.4 on 2020-04-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0016_auto_20200331_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='topics',
            field=models.ManyToManyField(to='discuss.Topic'),
        ),
        migrations.AlterField(
            model_name='content',
            name='topics',
            field=models.ManyToManyField(to='discuss.Topic'),
        ),
    ]
