# Generated by Django 3.0.4 on 2020-04-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0017_auto_20200401_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='topics',
            field=models.ManyToManyField(blank=True, to='discuss.Topic'),
        ),
        migrations.AlterField(
            model_name='content',
            name='topics',
            field=models.ManyToManyField(to='discuss.Topic'),
        ),
    ]
