# Generated by Django 3.0.4 on 2020-04-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0018_auto_20200401_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='contents',
            field=models.ManyToManyField(blank=True, related_name='comments', to='discuss.content'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='comments', to='discuss.Topic'),
        ),
        migrations.AlterField(
            model_name='content',
            name='topics',
            field=models.ManyToManyField(to='discuss.Topic'),
        ),
    ]
