# Generated by Django 3.0.4 on 2020-04-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0019_auto_20200403_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='comments', to='discuss.Topic'),
        ),
        migrations.AlterField(
            model_name='content',
            name='topics',
            field=models.ManyToManyField(to='discuss.Topic'),
        ),
    ]
