# Generated by Django 3.0.4 on 2020-04-13 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discuss', '0020_auto_20200411_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='comments', to='discuss.Topic'),
        ),
        migrations.AlterField(
            model_name='content',
            name='topics',
            field=models.ManyToManyField(to='discuss.Topic'),
        ),
    ]
