# Generated by Django 3.0.7 on 2020-07-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0007_ask_vote'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='asks_voted',
            field=models.ManyToManyField(related_name='asks_voted', to='discuss.ask'),
        ),
    ]
